song/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    # 프로필 url / follow url 구현
    path('profile/<username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

song/musics/urls.py
from django.urls import path, include
from . import views

app_name = 'musics'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:music_pk>/likes/', views.likes, name='likes'),

]

song/song/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('musics/', include('musics.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

song/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- 부트스트랩 설정 -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  <!-- css 연결 -->
  <link rel="stylesheet" href="{% static 'musics/css/base.css' %}">
  {% block static %}{% endblock static %}
  <!-- boxicon 연결-->
  <link rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
  <!-- font 연결-->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet">
  <title>Music</title>
</head>
<body>
  {% block nav %}
  <!-- 수정한 것 : 로고 이미지 넣으면 index로 연결, 오른쪽에 accounts 배치 -->
  <!-- 수정해야 할 것 : 메뉴바 어떻게 할지, accounts 항목 수정 (ex) 프로필 누르면 회원정보 수정 넣고 그런거)-->
  {% load static %}
  <nav class="navbar navbar-expand-lg" style="background-color: #e3f2fd;">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'musics:index' %}">
        <img 
        src="{% static 'musics/logo2.png' %}"
        alt="logo" width="80" height="80" class="d-inline-block align-text-top">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0 justify-content-end">
          <!--home-->
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'musics:index' %}">Home</a>
          </li>
          
          <!--create-->
          <li class="nav-item">
            {% if request.user.is_authenticated %}
            <a class="nav-link active" aria-current="page" href="{% url 'musics:create' %}">Create</a>
            {% else %}
            <a class="nav-link active" aria-current="page" href="{% url 'accounts:login' %}">Create</a>
            {% endif %}
          </li>

          {% if request.user.is_authenticated %}
          <!-- 계정 dropdown -->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              내 프로필
            </a>
            <!-- dropdown 항목들 -->
            <ul class="dropdown-menu" style="left:-60px">
              <!-- profile 들어가는 계정 -->
              <li>
                <a class="btn btn-outline-blue" href="{% url 'accounts:profile' user.username %}">
                <button type="submit" class="dropdown-item">계정</button>
                </a>
              </li> 
      
              <!-- logout 버튼 -->
              <li>
                <form class="dropdown-item" action="{% url 'accounts:logout' %}" method="POST">
                  {% csrf_token %}
                  <button type="submit" class="dropdown-item">Logout</button>
                </form>
              </li>
              <!-- 회원탈퇴 버튼 -->
              <li><hr class="dropdown-divider"></li>
              <li>
                <form class="dropdown-item" action="{% url 'accounts:delete' %}" method="POST">
                  {% csrf_token %}
                  <button type="submit" class="dropdown-item">회원탈퇴</button>
                </form>
              </li>
            </ul>
          </li>
        </ul>
        <!--이 부분이 고친 것 -->
        <ul class="nav justify-content-end align-items-center">
          
          {% comment %} <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'accounts:update' %}">회원정보수정</a>
          </li> 
>
          {% comment %} 수정사항 {% endcomment %}
          {% comment %} <li class="nav-item">
            <a href="{% url 'accounts:profile' user.username %}" class="d-flex-row">
              <div class="image text-center">
                <img src="{% static 'musics/base_profile.png' %}"
                alt="base_profile" width="50" height="40" class="rounded-circle">
              </div>
              <p>내 프로필</p>
            </a>
          </li> {% endcomment %}

          {% else %}
          <li class="nav-item">
            <a class="btn btn-outline-blue" href="{% url 'accounts:login' %}">Login</a>
          </li>
          {% endif %}    
        </ul>
      </div>
    </div>
  </nav>

  
  {% endblock nav %}

  {% block content %}
  {% endblock content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>
</html>