song/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    # 프로필 url / follow url 구현
    path('profile/<username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

song/musics/urls.py
from django.urls import path, include
from . import views

app_name = 'musics'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:music_pk>/likes/', views.likes, name='likes'),

]

song/song/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('musics/', include('musics.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

song/musics/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Music(models.Model):
    # 앨범 커버 이미지
    image = models.ImageField(blank=True)
    # 노래 제목
    title = models.CharField(max_length=20)
    # 가수명
    artist = models.CharField(max_length=20)
    # 노래 설명
    description = models.TextField()
    # 장르별
    genre = models.CharField(max_length=30)
    # 날씨별
    weather = models.CharField(max_length=30)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_musics')

class Comment(models.Model):
    music = models.ForeignKey(Music, on_delete=models.CASCADE) 
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)

song/musics/forms.py
from django import forms
from .models import Music, Comment

music_genre = [('전체', '전체'), ('발라드','발라드'), ('댄스', '댄스'), ('힙합','힙합'), ('재즈','재즈')]

music_weather = [('전체', '전체'), ('화창', '화창'), ('흐림', '흐림'), ('비', '비')]

# 뮤직폼 작성 - 장르와 날씨는 ChoiceField 사용
class MusicForm(forms.ModelForm):
    genre = forms.ChoiceField(
        choices = music_genre,
    )

    weather = forms.ChoiceField(
        choices = music_weather
    )

    class Meta:
        model = Music
        exclude = (
            'user',
            'like_users',
        )
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = (
            'music',
            'user',
        )

song/musics/views.py
from django.shortcuts import render, redirect
from .models import Music, Comment
from .forms import MusicForm, CommentForm
from django.views.decorators.http import require_http_methods

# Create your views here.
@require_http_methods(['GET'])
def index(request):
    musics = Music.objects.all()
    context = {
        'musics': musics,
    }
    return render(request, 'musics/index.html', context)

@require_http_methods(['GET'])
def detail(request, pk):
    music = Music.objects.get(pk=pk)
    comment_form = CommentForm()
    comments = music.comment_set.all()
    context = {
        'music' : music,
        'comment_form' : comment_form,
        'comments' : comments,
    }
    return render(request, 'musics/detail.html', context)

@require_http_methods(['POST','GET'])
def create(request):
    if request.method =='POST':
        form = MusicForm(request.POST, request.FILES)
        if form.is_valid():
            music = form.save(commit=False)
            music.user = request.user
            music.save()
            return redirect('musics:detail', music.pk) 
    else:
        form = MusicForm()
    context = {'form':form}
    return render(request, 'musics/create.html', context)

@require_http_methods(['POST','GET'])
def update(request, pk):
    music = Music.objects.get(pk=pk)
    if request.user == music.user:
        if request.method =='POST':
            form = MusicForm(request.POST, request.FILES, instance = music)
            if form.is_valid():
                music.save()
                return redirect('musics:detail', pk=music.pk)
        else:
            form = MusicForm(instance=music)
    else:
        return redirect('musics:detail', music.pk)
    context = {'form':form, 'music':music}
    return render(request, 'musics/update.html', context)

@require_http_methods(['POST'])
def delete(request, pk):
    music = Music.objects.get(pk=pk)
    if request.user == music.user:
        music.delete()
        return redirect('musics:index')
    return redirect('musics:detail', music.pk)

@require_http_methods(['POST'])
def comments_create(request, pk):
    if not request.user.is_authenticated:
        return redirect('accounts:login')
    
    music = Music.objects.get(pk = pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.music = music
        comment.user = request.user
        comment.save()
    return redirect('musics:detail', music.pk)

@require_http_methods(['POST'])
def comments_delete(request, pk, comment_pk):
    if not request.user.is_authenticated:
        return redirect('accounts:login')
    comment = Comment.objects.get(pk=comment_pk)
    if request.user == comment.user:
        comment.delete()
    return redirect('musics:detail', pk)

@require_http_methods(['POST'])
def likes(request, music_pk):
    if request.user.is_authenticated:
        music = Music.objects.get(pk=music_pk)
        if music.like_users.filter(pk=request.user.pk).exists():
            music.like_users.remove(request.user)
        else:
            music.like_users.add(request.user)
        return redirect('musics:index')
    return redirect('accounts:login')

song/musics/templates/musics/create.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <h3 style="text-align : center; padding-top: 30px;">REGISTER MUSIC</h3>
    <br>
    <div class="d-flex justify-content-center" 
        style="border:2px groove; border-radius:0.5em; width : 80%; height:80%; margin:0 auto; padding:20;">
      <form action="" method = "POST" enctype = "multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="생성">
      </form>
      <hr>
    </div>
    <div class='d-flex justify-content-center m-2'>
      <button class="btn" style="background-color:#CCEEFF" onclick="location.href={% url 'musics:index' %}">취소</button>
    </div>
  </div>
{% endblock content %}

song/musics/templates/musics/detail.html
{% extends 'base.html' %}

{% block content %}
  <h2>DETAIL</h2>
  <hr>
  {% if music.image %}
    <img src="{{music.image.url}}" alt="{{music.image}}">
  {% endif %}
  <p>제목 : {{ music.title }} </p>
  <p>가수 : {{ music.artist }} </p>
  <p>장르 : {{ music.genre }} </p>
  <p>{{ music.description }} </p>
  <hr>
  <form action="{% url 'musics:delete' music.pk %}" method='POST'>
    {% csrf_token %}
    <input type="submit" value='삭제'>
  </form>
  <a href="{% url 'musics:index' %}">[BACK]</a>
  <a href="{% url 'musics:update' music.pk %}">[수정하기]</a>

  <h3>댓글 목록</h3>
  
  {% if comments %}
    <p><b>{{comments|length}}개의 댓글</b></p>
  {% endif %}

  <ul>
    {% for comment in comments %}
    <li>
      {{comment.content}} - {{comment.user}}
      {% if request.user == comment.user %}
        <form action="{% url 'musics:comments_delete' music.pk comment.pk%}" method="POST">
          {% csrf_token %}
          <input type="submit" value="DELETE">
        </form>
      {% endif %}
    </li>
    {% empty %}
      <li>댓글이 없습니다</li>
    {% endfor %}
  </ul>
  <hr>
  {% if request.user.is_authenticated %}
    <form action="{% url 'musics:comments_create' music.pk %}" method="POST">
      {% csrf_token %}
      {{comment_form}}
      <input type="submit" value="저장">
    </form>
  {% else %}
    <a href="{% url 'accounts:login' %}">댓글을 작성하려면 로그인하세요</a>
  {% endif %}

{% endblock content %}

song/musics/templates/musics/index.html
{% extends 'base.html' %}
{% load static %}

{% block static %}
  <link rel="stylesheet" href="{% static 'musics/css/index.css' %}">
{% endblock static %}


{% block content %}
{% load static %}
<div class="songcontainer">
  {% for music in musics %}
    <p> {{ music.image }} </p>
    <p> 가수 : <a href="{% url 'musics:detail' music.pk %}">
      {{ music.artist }}
    </a></p>
    {% if request.user.is_authenticated %}
      <div>
        <form action="{% url 'musics:likes' music.pk %}" method="POST">
          {% csrf_token %}
          {% if request.user in music.like_users.all %}
            <input type="submit" value="좋아요 취소!">
          {% else %}
            <input type="submit" value="좋아요">
          {% endif %}
        </form>
      </div>
    {% endif %}
  {% endfor %}
</div>
{% endblock content %}

song/musics/templates/musics/update.html
{% extends 'base.html' %}

{% block content %}
  <h1>UPDATE</h1>
  <form action="{% url 'musics:update' music.pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value = '수정'>
  </form>
  <hr>
  <a href="{% url 'musics:detail' music.pk %}">[BACK]</a>
{% endblock content %}