song/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    # 프로필 url / follow url 구현
    path('profile/<username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

song/musics/urls.py
from django.urls import path, include
from . import views

app_name = 'musics'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:music_pk>/likes/', views.likes, name='likes'),

]

song/song/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('musics/', include('musics.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

song/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    # follow 모델 설정
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')

song/musics/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Music(models.Model):
    # 앨범 커버 이미지
    image = models.ImageField(blank=True)
    # 노래 제목
    title = models.CharField(max_length=20)
    # 가수명
    artist = models.CharField(max_length=20)
    # 노래 설명
    description = models.TextField()
    # 장르별
    genre = models.CharField(max_length=30)
    # 날씨별
    weather = models.CharField(max_length=30)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_musics')

class Comment(models.Model):
    music = models.ForeignKey(Music, on_delete=models.CASCADE) 
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)

song/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()

class CustomUserChangeForm(UserCreationForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('email', 'first_name', 'last_name')

song/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import get_user_model
from django.views.decorators.http import require_http_methods
from .forms import CustomUserCreationForm, CustomUserChangeForm

# Create your views here.
@require_http_methods(['POST', 'GET'])
def login(request):
    if request.user.is_authenticated:
        return redirect('musics:index')
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('musics:index')
    else:
        form = AuthenticationForm()
    context = {'form' : form}
    return render(request, 'accounts/login.html', context)

@require_http_methods(['POST'])
def logout(request):
    auth_logout(request)
    return redirect('musics:index')

@require_http_methods(['POST', 'GET'])
def signup(request):
    if request.method =='POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('musics:index')
    else:
        form = CustomUserCreationForm()
    context = {'form' : form}
    return render(request, 'accounts/signup.html', context)

@require_http_methods(['POST'])
def delete(request):
    request.user.delete()
    return redirect('musics:index')

@require_http_methods(['POST', 'GET'])
def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('musics:index')
    else:
        form = CustomUserChangeForm(instance = request.user)
    context={'form':form}
    return render(request, 'accounts/update.html', context)

@require_http_methods(['POST', 'GET'])
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('musics:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {'form' : form}
    return render (request, 'accounts/change_password.html', context)


# profile view 함수 구현
@require_http_methods(['GET'])
def profile(request, username):
    person = get_user_model().objects.get(username=username)
    context = {
        'person' : person,
    }
    return render(request, 'accounts/profile.html', context)

# follow view 함수 구현
@require_http_methods(['POST'])
def follow(request, user_pk):
    if request.user.is_authenticated:
        person = get_user_model().objects.get(pk=user_pk)
        if person != request.user:
            if person.followers.filter(pk=request.user.pk).exists():
                person.followers.remove(request.user)
            else:
                person.followers.add(request.user)
        return redirect('accounts:profile', person.username)
    return redirect('accounts:login')

song/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block content %}
  <h1>비밀번호 변경</h1>
  <form action="{% url 'accounts:change_password' %}" method = 'POST'>
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
  </form>
{% endblock content %}

song/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block static %}
  <link rel="stylesheet" href="{% static 'musics/css/login.css' %}">
{% endblock static %}


{% block content %}
<div class="center">
  <h1>Login</h1>
  <form action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
      <div class="txt_field">
        {{ form.username }}
        <span></span>
        <label>Username</label>
      </div>
      <div class="txt_field">
        {{ form.password }}
        <span></span>
        <label>Password</label>
      </div>
      {% if form.errors %}
      <p class="error">아이디, 비밀번호가 일치하지 않습니다. 다시 시도해주세요.</p>
      {% endif %}
      <div class="pass">Forgot Password?</div>
      <input type="submit" value="Login">
      <div class="signup_link">
        Not a member? <a href="{% url 'accounts:signup' %}">Signup</a>
      </div>
  </form>
</div>




{% comment %} <div class="loginpage">
  <div class="container my-5" >
      <h3 class="my-3">Login</h3>
      <hr>
      <!-- 만약 폼에 에러가 나타나면 에러 메세지 출력-->
      {% if form.errors %}
      <p style="color:red;">아이디, 비밀번호가 일치하지 않습니다. 다시 시도해주세요.</p>
      {% endif %}

      <!-- 로그인 폼 꾸미기 -->
      <form action="{% url 'accounts:login' %}" method="post">
      {% csrf_token %}
      <div class="form-group row">
              <label for="staticEmail" class="col-sm-2 col-form-label">ID</label>
              <div class="col-sm-10 mt-1">
                {{ form.username }}
              </div>
            </div>
            <div class="form-group row">
              <label for="inputPassword" class="col-sm-2 col-form-label">Password</label>
              <div class="col-sm-10 mt-1">
                  {{ form.password }}
              </div>
            </div>
      <button class="btn btn-info mt-3" type="submit"> Sign in </button>
      </form>
  </div>
</div> {% endcomment %}
{% endblock %}

song/accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
  <h1>{{ person.username }}님의 프로필</h1>
  <hr>

  <div class="main_image">
    <img src="{% static 'musics/lecord.png' %}"alt="base_profile" width="1400" height="1000" class="border position-relative img-fluid">
  
  
    <div class="main_profile border top-50 start-50 translate-middle badge" style="position: absolute;">
      <div class="d-flex justify-content-end">

        <div class="like_music me-4 text-center">
          {{person.like_musics.count}}
          <p>좋아하는 노래수</p>
        </div>

        <div class="followers me-4 text-center">
          {{ person.followers.count}}
          <p>팔로워</p>
        </div>
    
        <div class="following me-4 text-center">
          {{ person.followings.count }}
          <p>팔로잉</p>
        </div>
      </div>
      <form class="d-flex justify-content-end pe-3" action="{% url 'accounts:follow' person.pk %}" method='POST'>
        {% csrf_token %}
        {% if request.user in person.followers.all %}
          <button type="submit" class="btn btn-danger rounded-pill">언팔로우</button>
        {% else %}
          <button type="submit" class="btn btn-primary rounded-2" style="width : 200px;" >팔로우</button>
        {% endif %}
      </form>
    </div> 
    
  </div>
  <br>
 
  <br>
  <h5>{{ person.username }}님이 작성한 게시글</h5>
  {% for music in person.music_set.all %}

  <div class="card">
    <div class="card-body">
        <h5 class="card-title">{{ music.title }}</h5>
        <p class="card-text">{{ music.discription }}</p>
        <a href="{% url 'musics:detail' music.pk %}" class="btn btn-primary">자세히 보기</a>

    </div>
  </div>
  {% endfor %}

  <hr><br><br>
  <h5>{{ person.username }}님이 좋아한 노래래</h5>
  {% for music in person.like_musics.all %}
  <div class="card">
    <div class="card-body">
        <h5 class="card-title">{{ music.title }}</h5>
        <p class="card-text">{{ music.content }}</p>
        <a href="{% url 'musics:detail' music.pk %}" class="btn btn-primary">자세히 보기</a>
    </div>
  </div>
  {% endfor %}
  <hr><br><br>

  <a href="{% url 'musics:index' %}" class='btn btn-success'>목록보기</a>

{% endblock content %}

song/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}

{% block static %}
  <link rel="stylesheet" href="{% static 'musics/css/signup.css' %}">
{% endblock static %}

{% block content %}
<div class="center">
  <h1>Sign Up</h1>
  <form action="{% url 'accounts:signup' %}" method="post">
    {% csrf_token %}
      <div class="txt_field">
        {{ form.username }}
        <span></span>
        <label>Username</label>
      </div>
      <div class="txt_field">
        {{ form.password1 }}
        <span></span>
        <label>Create Password</label>
      </div>
      <div class="txt_field">
        {{ form.password2 }}
        <span></span>
        <label>Confirm Password</label>
      </div>
      <input type="submit" value="Signup">
      <div class="signup_link">
        Already a user? <a href="{% url 'accounts:login' %}">Login</a>
      </div>
  </form>
</div>
{% endblock content %}

song/accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% block content %}
  <h1>회원정보수정</h1>
  <form action="{% url 'accounts:update' %}" method = "POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
  </form>
{% endblock content %}